---
pdf_document: default
author: "Jing Ying"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
title: "Week 9 Code-along and Challenge"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 9 Code 
<br>

## I.  
<br>

```{r, eval=TRUE,echo=TRUE}
# Slide 8 

library(tidyverse)

tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360,
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583)

tidydata

nontidydata <- tribble(
  ~country,~year,~rate, 
  "Afghanistan", 1999, "745/19987071", 
  "Afghanistan", 2000, "2666/20595360", 
  "Brazil", 1999, "37737/172006362", 
  "Brazil", 2000, "80488/174504898", 
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583")

nontidydata

```

```{r, eval=TRUE,echo=TRUE}
# Slide 11 

nontidydata

tidieddata <- nontidydata %>% 
  separate(rate,into=c("cases","population"),
           sep="/")

tidieddata

```

```{r, eval=TRUE,echo=TRUE}
# Slide 12 

newtidieddata <- tidieddata %>%
 pivot_longer(
   cols = cases:population,
   names_to = "measurement",
   values_to = "value"
   )

newtidieddata

```

```{r, eval=TRUE,echo=TRUE}
# Slide 14 

df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
  )

df

df %>%
 pivot_longer(
   cols = bp1:bp2,
   names_to = "measurement",
   values_to = "value"
   )

```

```{r, eval=TRUE,echo=TRUE}
# Slide 18 

newtidieddata

newtidieddata %>% 
 pivot_wider(names_from="measurement",
             values_from="value")

```

```{r, eval=TRUE,echo=TRUE}
# Slide 19 

df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115, 
  "A", "bp2", 120,
  "A", "bp3", 105
  )

df

df %>% 
 pivot_wider(
   names_from = measurement,
   values_from = value
   )

```

# Week 9 Challenge

```{r, eval=TRUE,echo=TRUE}
# Part 1

billboard


```

```{r, eval=TRUE,echo=TRUE}
# Part 1

billboardweek <- billboard %>% 
  pivot_longer(
    starts_with("wk"),
    names_to = "week",
    values_to = "rank",
    values_drop_na = TRUE
    ) %>% mutate(week=parse_number(week))

billboardweek

ggplot(billboardweek, aes(x = week, y = rank)) +
  geom_line()

```

```{r, eval=TRUE,echo=TRUE}
# Part 2

cms_patient_experience

```

```{r, eval=TRUE,echo=TRUE}
# Part 2

cms_patient_experience_wide <- cms_patient_experience %>%
  pivot_wider(
    names_from = measure_cd, 
    values_from = prf_rate, 
    id_cols = starts_with("org")
    )

cms_patient_experience_wide

```
